{
 "title": "Nginx dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Intervals",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Nginx http requests total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nginx_http_requests_total" }
   ]
  },
  {
   "title": "Nginx Status - is up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "Nginx Active connections ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "nginx_connections_active" }
   ]
  },
  {
   "title": "Nginx Waiting connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "nginx_connections_waiting" }
   ]
  },
  {
   "title": "Nginx CPU limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", pod=~\"nginx.*\"}"
    }
   ]
  },
  {
   "title": "Nginx Memory limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", pod=~\"nginx.*\"}"
    }
   ]
  },
  {
   "title": "Nginx CPU requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\", pod=~\"nginx.*\"}"
    }
   ]
  },
  {
   "title": "Nginx Memory requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\", pod=~\"nginx.*\"}"
    }
   ]
  },
  {
   "title": "Nginx memory usage in MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"nginx.*\"}/1024/1024"
    }
   ]
  },
  {
   "title": "Nginx cpu usage last $Intervals minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"nginx.*\"}[$Intervals])"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "kube_pod_status_ready{pod=~\"nginx.*\"}"
    }
   ]
  }
 ]
}